minecraft-server:
  image: itzg/minecraft-server
  ports:
    - "25565:25565"
  volumes:
    - "./data:/data"
  environment:
    EULA: "TRUE"
    MODE: "survival"
    ENABLE_RCON: "true"
    ENABLE_ROLLING_LOGS: "true"
  tty: true
  stdin_open: true
  restart: always
